version: "3.7"

services:
  frontend:
    image: node:16-alpine
    command: ["yarn", "start"]
    ports:
      - "5000:5000"
      # For webpack dev server
      - "3035:3035"
    volumes:
      - ./client:/app

  backend:
    image: node:16-alpine
    depends_on:
      - postgres
    command: ["yarn", "start"]
    environment: 
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=jira_development
      - JWT_SECRET=thisisnotasecret
    volumes:
      - ./api:/app

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}
